import {useEffect, useState} from 'react';
import {createPortal} from 'react-dom';
const avatars = ['🎧','🐱','🦊','🐼','🐰','🐻','👽','🌙'];
import {songs} from '@/lib/songs';
import type {Community} from '@/lib/community';

export function CommunityPanel({data,id,enter,leave,act,view,error,busy,openHost}:{data:Community|null;id:string;enter:(id:string,merge:boolean)=>void;leave:()=>void;act:(path:string,body:Record<string,unknown>)=>Promise<boolean>;view:string;error:string;busy:boolean;openHost:()=>void}){
 const [input,setInput]=useState(''),[merge,setMerge]=useState(false),[rank,setRank]=useState('copies'),[title,setTitle]=useState(''),[artist,setArtist]=useState(''),[open,setOpen]=useState(false);
 const [avatar,setAvatar]=useState('🎧');
 const [slot,setSlot]=useState<HTMLElement|null>(null);
 useEffect(()=>{setSlot(document.getElementById('profile-slot'));try{const saved=localStorage.getItem('song-avatar');if(saved && avatars.includes(saved))setAvatar(saved);}catch{}},[]);
 function chooseAvatar(value:string){setAvatar(value);try{localStorage.setItem('song-avatar',value);}catch{}}
 return <>
  {slot && createPortal(<div className="profile-wrap"><button className={'profile-avatar'+(id?' signed':'')} aria-expanded={open} aria-label={id?'打开用户档案菜单':'打开登录菜单'} onClick={()=>setOpen(v=>!v)}><span>{avatar}</span><i /></button>
   {open&&<div className="profile-menu" role="dialog" aria-label="用户档案">{id?<><p className="profile-kicker">当前档案</p><strong>{id}</strong><p className="profile-help">收藏和榜单数据已连接到这个 ID。</p><button className="profile-action secondary" onClick={()=>{leave();setOpen(false)}} disabled={busy}>退出 / 更换 ID</button></>:<form onSubmit={e=>{e.preventDefault();enter(input,merge);setOpen(false)}}><p className="profile-kicker">免密登录</p><h2>进入你的档案</h2><p className="profile-help">输入 ID 即可保存和恢复收藏。</p><input required minLength={3} maxLength={40} value={input} onChange={e=>setInput(e.target.value)} placeholder="输入 ID，例如 九橘001" aria-label="用户ID"/><label className="merge-option"><input type="checkbox" checked={merge} onChange={e=>setMerge(e.target.checked)} />合并本机已有收藏</label><button className="profile-action" disabled={busy}>进入档案</button></form>}<button className="profile-action host-menu-entry" onClick={()=>{setOpen(false);openHost()}}>进入主播后台</button><div className="avatar-picker"><p>选择头像</p><div>{avatars.map((value,index)=><button key={value} type="button" className={"avatar-choice avatar-tone-"+index} aria-label={"选择头像 "+value} aria-pressed={avatar===value} onClick={()=>chooseAvatar(value)}>{value}</button>)}</div><small>保存在当前浏览器</small></div>{error&&<p className="profile-error" role="alert">{error}</p>}</div>}
  </div>,slot)}
  {(view==='ranking'||view==='wishes')&&<section className={'community-panel community-panel-'+view}>{error&&<p className="profile-error" role="alert">{error}</p>}
   {view==='ranking'&&<><div className="community-heading"><div><p className="eyebrow">COMMUNITY RANKINGS</p><h2>大家正在点什么</h2></div><div className="rank-switch"><button aria-pressed={rank==='copies'} onClick={()=>setRank('copies')}>点歌榜</button><button aria-pressed={rank==='likes'} onClick={()=>setRank('likes')}>喜爱榜</button></div></div>{!data?<p className="community-muted">{error?'共享榜单暂不可用':'共享榜单连接中…'}</p>:<ol>{data[rank==='copies'?'copies':'likes'].map(row=><li key={row.song}><span><b>{String(row.song).padStart(3,'0')}</b>{songs.find(s=>s.id===row.song)?.title}{(()=>{const s=songs.find(x=>x.id===row.song);return s?.artist&&<small className="song-artist">{s.artist}</small>})()}</span><em>{row.count} {rank==='copies'?'次点歌':'人喜欢'}</em></li>)}</ol>}</>}
   {view==='wishes'&&<><div className="community-heading"><div><p className="eyebrow">WISH LIST</p><h2>许愿学歌</h2><p>写下想听的歌，大家可以一起支持。</p></div></div><form className="wish-form" onSubmit={async e=>{e.preventDefault();if(await act('wish',{title,artist})){setTitle('');setArtist('');}}}><input aria-label="许愿歌名" required maxLength={100} placeholder="想听主播学哪首歌？" value={title} onChange={e=>setTitle(e.target.value)}/><input aria-label="歌手（选填）" maxLength={80} placeholder="歌手（选填）" value={artist} onChange={e=>setArtist(e.target.value)}/><button disabled={!id||busy}>提交许愿</button></form>{!id&&<p className="community-muted">登录后才能提交许愿或支持。</p>}{!data?<p className="community-muted">{error?'许愿榜暂不可用':'许愿榜连接中…'}</p>:<ol>{data.wishes.map(w=><li key={w.id}><span><b>{w.title}</b>{w.artist&&<small> · {w.artist}</small>}</span><button disabled={!id||busy} aria-pressed={data.supported.includes(w.id)} onClick={()=>void act('vote',{wish:w.id,active:!data.supported.includes(w.id)})}>{data.supported.includes(w.id)?'已支持 · 取消':'+1 支持'}（{w.count}）</button></li>)}</ol>}</>}
  </section>}
 </>;
}
