'use client';
import {useEffect,useMemo,useState} from 'react';
import {ChevronUp,Mic2,Pause,Play,Plus,Radio,RotateCcw,Search,SkipForward} from 'lucide-react';
import {replaceSongs,songs,type Song} from '@/lib/songs';
import {cachedCatalog,hostAuthenticate,hostCatalogAction,loadCatalog,type CatalogSong} from '@/lib/catalog';
import {loadRequests,requestEvent,saveRequests,type RequestStatus,type SongRequest} from '@/lib/request-demo';

const labels:Record<RequestStatus,string>={pending:'待审核',queued:'排队中',active:'进行中',paused:'已暂停',done:'已完成',rejected:'已拒绝'};
const activeStatuses:RequestStatus[]=['pending','queued','active','paused'];
const demoCatalogKey='jiuju-host-catalog-demo-v1';
export function AudienceQueue({user}:{user:string}){
 const [list,setList]=useState<SongRequest[]>([]);
 const refresh=()=>setList(loadRequests());
 useEffect(()=>{refresh();window.addEventListener(requestEvent,refresh);window.addEventListener('storage',refresh);return()=>{window.removeEventListener(requestEvent,refresh);window.removeEventListener('storage',refresh)}},[]);
 const queue=useMemo(()=>list.filter(item=>activeStatuses.includes(item.status)).sort((a,b)=>{
  const aNow=a.status==='active'||a.status==='paused'?0:1,bNow=b.status==='active'||b.status==='paused'?0:1;
  return aNow-bNow||a.createdAt-b.createdAt;
 }),[list]);
 const mine=queue.findIndex(item=>item.user===user);
 return <section className="audience-queue" aria-labelledby="audience-queue-title"><div className="audience-queue-heading"><div><p className="eyebrow">UP NEXT</p><h1 id="audience-queue-title">待播单</h1><p>点唱和点放按提交时间统一排队，主播处理后这里会立即更新。</p></div><div className={'my-position '+(mine>=0?'has-position':'')}><span>{!user?'登录后查看自己的排位':mine>=0?'你的歌排在':'你还没有正在排队的歌'}</span>{user&&mine>=0&&<><strong>第 {mine+1} 位</strong><small>{mine===0?'马上轮到你':`前面还有 ${mine} 首`}</small></>}</div></div><div className="audience-queue-list">{queue.map((item,index)=>{const song=songs.find(value=>value.id===item.song);const isMine=!!user&&item.user===user;return <article key={item.id} className={'audience-queue-row '+item.status+(isMine?' mine':'')}><b>{String(index+1).padStart(2,'0')}</b><span className={'queue-kind '+item.kind}>{item.kind==='sing'?<Mic2/>:<Play/>}{item.kind==='sing'?'点唱':'点放'}</span><div><strong>{song?.title||`歌曲 #${item.song}`}</strong><span>{item.user}{isMine?'（我）':''} · {labels[item.status]}</span></div>{isMine&&<em>我的点歌</em>}</article>})}{!queue.length&&<div className="audience-queue-empty"><Radio/><h2>待播单还是空的</h2><p>去歌曲列表选一首，提交点唱或点放吧。</p></div>}</div></section>
}

function SongManager({token}:{token:string}){
 const [catalog,setCatalog]=useState<CatalogSong[]>([]),[query,setQuery]=useState(''),[title,setTitle]=useState(''),[note,setNote]=useState(''),[sc,setSC]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const demo=token==='local-demo';
 const refresh=async()=>{try{let value:CatalogSong[];if(demo){try{value=JSON.parse(localStorage.getItem(demoCatalogKey)||'null')||cachedCatalog()}catch{value=cachedCatalog()}}else value=(await loadCatalog(true,token)).songs;setCatalog(value)}catch(error){setMessage((error as Error).message)}};
 useEffect(()=>{void refresh()},[token]);
 const visible=catalog.filter(song=>!query.trim()||song.title.toLowerCase().includes(query.trim().toLowerCase())||String(song.id)===query.trim().replace(/^#/,''));
 function saveDemo(next:CatalogSong[]){setCatalog(next);const active=next.filter(song=>song.active);try{localStorage.setItem(demoCatalogKey,JSON.stringify(next));localStorage.setItem('jiuju-song-catalog-v1',JSON.stringify(active))}catch{}replaceSongs(active)}
 async function add(){if(!title.trim()||busy)return;setBusy(true);setMessage('');try{if(demo){const nextId=Math.max(0,...catalog.map(song=>song.id))+1;saveDemo([...catalog,{id:nextId,title:title.trim(),note:note.trim(),isSC:sc,active:true}]);setMessage(`已新增 #${nextId} ${title.trim()}`)}else{const result=await hostCatalogAction('addSong',{token,title:title.trim(),note:note.trim(),isSC:sc});setMessage(`已新增 #${result.song.id} ${result.song.title}`);await refresh()}setTitle('');setNote('');setSC(false)}catch(error){setMessage((error as Error).message)}finally{setBusy(false)}}
 async function toggle(song:CatalogSong){if(busy)return;setBusy(true);setMessage('');try{if(demo){saveDemo(catalog.map(item=>item.id===song.id?{...item,active:!item.active}:item))}else{await hostCatalogAction('setSongActive',{token,songId:song.id,active:!song.active});await refresh()}setMessage(`${song.title}已${song.active?'下架':'恢复上架'}`)}catch(error){setMessage((error as Error).message)}finally{setBusy(false)}}
 return <section className="song-manager"><div className="song-manager-title"><div><p className="eyebrow">SONG CATALOG</p><h2>歌曲管理</h2></div><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索编号或歌名"/></label></div><form className="song-add" onSubmit={event=>{event.preventDefault();void add()}}><input required maxLength={100} value={title} onChange={event=>setTitle(event.target.value)} placeholder="新歌名称" aria-label="新歌名称"/><input maxLength={200} value={note} onChange={event=>setNote(event.target.value)} placeholder="备注（选填）" aria-label="歌曲备注"/><label><input type="checkbox" checked={sc} onChange={event=>setSC(event.target.checked)}/>SC</label><button disabled={busy}><Plus/>新增歌曲</button></form>{message&&<p className="song-manager-message" role="status">{message}</p>}<div className="song-admin-list">{visible.map(song=><article key={song.id} className={song.active?'':'inactive'}><b>#{String(song.id).padStart(3,'0')}</b><div><strong>{song.title}</strong><span>{song.isSC?'SC · ':''}{song.note||'无备注'}</span></div><em>{song.active?'已上架':'已下架'}</em><button disabled={busy} onClick={()=>void toggle(song)}>{song.active?'下架':'恢复'}</button></article>)}</div></section>
}

export function HostConsole({onClose}:{onClose:()=>void}){
 const [list,setList]=useState<SongRequest[]>([]);const [token,setToken]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [loginBusy,setLoginBusy]=useState(false);
 const refresh=()=>setList(loadRequests());useEffect(()=>{refresh();const timer=setInterval(refresh,30000);window.addEventListener(requestEvent,refresh);return()=>{clearInterval(timer);window.removeEventListener(requestEvent,refresh)}},[]);
 const active=list.filter(item=>!['done','rejected'].includes(item.status));const history=list.filter(item=>['done','rejected'].includes(item.status));
 const now=active.find(item=>item.status==='active'||item.status==='paused');
 function update(id:string,status:RequestStatus){let next=loadRequests().map(item=>item.id===id?{...item,status}:item);if(status==='active')next=next.map(item=>item.id!==id&&item.status==='active'?{...item,status:'queued'}:item);saveRequests(next)}
 function move(id:string){const next=loadRequests();const index=next.findIndex(item=>item.id===id);if(index>0){[next[index-1],next[index]]=[next[index],next[index-1]];saveRequests(next)}}
 async function login(){if(loginBusy)return;setLoginBusy(true);setError('');const env=(import.meta as ImportMeta&{env:Record<string,string|boolean>}).env;if(env.DEV&&env.VITE_HOST_DEMO_PASSWORD===password){setToken('local-demo');setPassword('');setLoginBusy(false);return}try{const result=await hostAuthenticate(password);setToken(result.token);setPassword('')}catch(err){setError((err as Error).message)}finally{setLoginBusy(false)}}
 if(!token)return <div className="host-shell"><div className="host-login"><Radio/><p className="eyebrow">HOST CONTROL</p><h1>主播控制台</h1><p>请输入云端配置的主播密码</p><input type="password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void login()}} placeholder="输入主播密码"/><button disabled={loginBusy} onClick={()=>void login()}>{loginBusy?'验证中…':'进入后台'}</button>{error&&<span>{error}</span>}<button className="host-back" onClick={onClose}>返回歌单</button></div></div>;
 return <div className="host-shell"><header className="host-header"><div><p className="eyebrow">LIVE SONG DESK</p><h1>主播控制台</h1></div><div><span className="live-dot"/>{token==='local-demo'?'本地演示':'云端已验证'}<button onClick={refresh}>刷新</button><button onClick={onClose}>返回歌单</button></div></header><main className="host-main"><section className="now-playing"><div><p className="eyebrow">NOW HANDLING</p>{now?<><span>{now.kind==='sing'?'正在演唱':'正在播放'}</span><h2>{songs.find(s=>s.id===now.song)?.title}</h2><p>{now.user} 点的 · {now.kind==='sing'?'点唱':'点放'}</p></>:<><span>当前空闲</span><h2>等待下一首</h2><p>从下面的队列选择开始</p></>}</div>{now&&<div className="player-controls"><button onClick={()=>update(now.id,now.status==='paused'?'active':'paused')}>{now.status==='paused'?<Play/>:<Pause/>}</button><button onClick={()=>update(now.id,'done')}><SkipForward/></button></div>}</section><div className="host-stats"><div><b>{active.filter(x=>x.status==='pending').length}</b><span>待审核</span></div><div><b>{active.filter(x=>x.kind==='play').length}</b><span>点放</span></div><div><b>{active.filter(x=>x.kind==='sing').length}</b><span>点唱</span></div></div><section className="queue-panel"><div className="queue-title"><div><p className="eyebrow">REQUEST QUEUE</p><h2>点歌队列</h2></div><span>每30秒自动刷新 · 可手动调整顺序</span></div><div className="queue-list">{active.map((item,index)=><article key={item.id} className={'queue-row '+item.status}><b className="queue-position">{String(index+1).padStart(2,'0')}</b><div className={'queue-kind '+item.kind}>{item.kind==='sing'?<Mic2/>:<Play/>}{item.kind==='sing'?'点唱':'点放'}</div><div className="queue-song"><strong>{songs.find(s=>s.id===item.song)?.title}</strong><span>{item.user} · {labels[item.status]}</span></div><div className="queue-actions">{item.status==='pending'?<><button className="accept" onClick={()=>update(item.id,'queued')}>接受</button><button onClick={()=>update(item.id,'rejected')}>拒绝</button></>:<><button title="置顶" onClick={()=>move(item.id)}><ChevronUp/></button><button className="accept" onClick={()=>update(item.id,'active')}>{item.kind==='sing'?'开始唱':'播放'}</button><button onClick={()=>update(item.id,'done')}>完成</button></>}</div></article>)}{!active.length&&<p className="queue-empty">目前没有等待中的点歌</p>}</div></section>{history.length>0&&<section className="history-panel"><h3>最近处理</h3>{history.slice(-5).reverse().map(item=><span key={item.id}>{songs.find(s=>s.id===item.song)?.title} · {labels[item.status]}</span>)}<button onClick={()=>saveRequests(list.filter(item=>!['done','rejected'].includes(item.status)))}><RotateCcw/>清空已完成</button></section>}<SongManager token={token}/></main></div>
}
