'use client';
import {useEffect,useState} from 'react';
import {MonitorPlay,Plus,Search} from 'lucide-react';
import {replaceSongs} from '@/lib/songs';
import {cachedCatalog,hostCatalogAction,loadCatalog,type CatalogSong} from '@/lib/catalog';
const demoCatalogKey='jiuju-host-catalog-demo-v1';
export function SongManager({token}:{token:string}){
 const [catalog,setCatalog]=useState<CatalogSong[]>([]),[query,setQuery]=useState(''),[title,setTitle]=useState(''),[note,setNote]=useState(''),[url,setUrl]=useState(''),[editingId,setEditingId]=useState<number|null>(null),[editingUrl,setEditingUrl]=useState(''),[sc,setSC]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const demo=token==='local-demo';
 const publishCatalog=(value:CatalogSong[])=>window.dispatchEvent(new CustomEvent('song-catalog-changed',{detail:value.filter(song=>song.active)}));
 const refresh=async()=>{try{let value:CatalogSong[];if(demo){try{value=JSON.parse(localStorage.getItem(demoCatalogKey)||'null')||cachedCatalog()}catch{value=cachedCatalog()}}else value=(await loadCatalog(true,token)).songs;setCatalog(value);return value}catch(error){setMessage((error as Error).message);return null}};
 useEffect(()=>{void refresh()},[token]);
 const visible=catalog.filter(song=>!query.trim()||song.title.toLowerCase().includes(query.trim().toLowerCase())||String(song.id)===query.trim().replace(/^#/,''));
 function saveDemo(next:CatalogSong[]){setCatalog(next);const active=next.filter(song=>song.active);try{localStorage.setItem(demoCatalogKey,JSON.stringify(next));localStorage.setItem('jiuju-song-catalog-v1',JSON.stringify(active))}catch{}replaceSongs(active);publishCatalog(next)}
 async function add(){if(!title.trim()||busy)return;setBusy(true);setMessage('');try{if(url.trim()&&!/^https?:\/\/\S+$/i.test(url.trim()))throw Error('视频链接必须以 http:// 或 https:// 开头');if(demo){const nextId=Math.max(0,...catalog.map(song=>song.id))+1;saveDemo([...catalog,{id:nextId,title:title.trim(),note:note.trim(),url:url.trim(),isSC:sc,active:true}]);setMessage(`已新增 #${nextId} ${title.trim()}`)}else{const result=await hostCatalogAction('addSong',{token,title:title.trim(),note:note.trim(),url:url.trim(),isSC:sc});setMessage(`已新增 #${result.song.id} ${result.song.title}`);const next=await refresh();if(next)publishCatalog(next)}setTitle('');setNote('');setUrl('');setSC(false)}catch(error){setMessage((error as Error).message)}finally{setBusy(false)}}
 async function toggle(song:CatalogSong){if(busy)return;setBusy(true);setMessage('');try{if(demo){saveDemo(catalog.map(item=>item.id===song.id?{...item,active:!item.active}:item))}else{await hostCatalogAction('setSongActive',{token,songId:song.id,active:!song.active});const next=await refresh();if(next)publishCatalog(next)}setMessage(`${song.title}已${song.active?'下架':'恢复上架'}`)}catch(error){setMessage((error as Error).message)}finally{setBusy(false)}}
 async function saveUrl(song:CatalogSong){const nextUrl=editingUrl.trim();if(nextUrl&&!/^https?:\/\/\S+$/i.test(nextUrl)){setMessage('视频链接必须以 http:// 或 https:// 开头');return}setBusy(true);setMessage('');try{if(demo)saveDemo(catalog.map(item=>item.id===song.id?{...item,url:nextUrl}:item));else{await hostCatalogAction('setSongUrl',{token,songId:song.id,url:nextUrl});const next=await refresh();if(next)publishCatalog(next)}setEditingId(null);setMessage(`${song.title}的视频链接已保存`)}catch(error){setMessage((error as Error).message)}finally{setBusy(false)}}
 return <section className="song-manager"><div className="song-manager-title"><div><p className="eyebrow">SONG CATALOG</p><h2>歌曲管理</h2></div><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索编号或歌名"/></label></div><form className="song-add" onSubmit={event=>{event.preventDefault();void add()}}><input required maxLength={100} value={title} onChange={event=>setTitle(event.target.value)} placeholder="新歌名称" aria-label="新歌名称"/><input maxLength={200} value={note} onChange={event=>setNote(event.target.value)} placeholder="备注（选填）" aria-label="歌曲备注"/><input type="url" maxLength={500} value={url} onChange={event=>setUrl(event.target.value)} placeholder="视频链接（选填）" aria-label="视频链接"/><label><input type="checkbox" checked={sc} onChange={event=>setSC(event.target.checked)}/>SC</label><button disabled={busy}><Plus/>新增歌曲</button></form>{message&&<p className="song-manager-message" role="status">{message}</p>}<div className="song-admin-list">{visible.map(song=><article key={song.id} className={song.active?'':'inactive'}><b>#{String(song.id).padStart(3,'0')}</b><div><strong>{song.title}</strong><span>{song.isSC?'SC · ':''}{song.note||'无备注'}{song.url?' · 已添加视频':''}</span></div><div className="admin-link-actions"><button disabled={busy} onClick={()=>{setEditingId(song.id);setEditingUrl(song.url||'');setMessage('')}}>链接</button>{song.url&&/^https?:\/\//i.test(song.url)&&<a className="admin-video-link" href={song.url} target="_blank" rel="noopener noreferrer" title="打开视频播放"><MonitorPlay/></a>}</div><em>{song.active?'已上架':'已下架'}</em><button disabled={busy} onClick={()=>void toggle(song)}>{song.active?'下架':'恢复'}</button>{editingId===song.id&&<div className="song-url-editor"><input type="url" aria-label={`${song.title}的视频链接`} placeholder="https://www.bilibili.com/video/..." value={editingUrl} onChange={event=>setEditingUrl(event.target.value)}/><button disabled={busy} onClick={()=>void saveUrl(song)}>保存链接</button><button onClick={()=>setEditingId(null)}>取消</button></div>}</article>)}</div></section>
}
